const themes = {
  adventure: {
    id: "adventure",
    label: "Adventure",
    description: "Heroic RPG-inspired experience",
    icon: "✨",
    fonts: { heading: "'Cinzel', serif", body: "'Quicksand', sans-serif" },
    vocab: {
      appTitle: "🎯 GOHABIT 🎯",
      appSubtitle: "Your Journey to Glory Awaits",
      appTagline: "GoHabit",
      loginTitle: "Welcome to GoHabit",
      loginSubtitle: "Sign in with Google to continue your habit journey.",
      loginButton: "Login With Google",
      loginButtonApple: "Login With Apple",
      appleLoginComingSoonTitle: "Coming Soon",
      appleLoginComingSoonDesc: "Apple Sign-In is currently in development. Stay tuned!",
      loadingText: "Initializing world...",
      logoutTitle: "Abandon Quest?",
      logoutMessage: "Your progress is saved. You can return to the realm at any time.",
      logoutStay: "Stay",
      logoutConfirm: "Logout",
      deleteProfileButton: "Delete My Profile",
      deleteProfileTitle: "Delete Profile Permanently?",
      deleteProfileWarningBadge: "PERMANENT DATA DELETION",
      deleteProfileDesc: "This is a full and irreversible deletion of your profile and all your data: progress, XP, streak, habits, and quests.",
      deleteProfileCannotUndo: "After deletion, recovery is not possible.",
      deleteProfileConfirm: "Yes, Permanently Delete",
      deleteProfileCancel: "No, Keep My Profile",
      levelLabel: "Level",
      levelShort: "LEVEL",
      levelProgress: "Level Progress",
      xpLabel: "XP",
      dailyBoard: "Daily Board",
      currentStreak: "Current Streak",
      todaysItems: "Today's Quests",
      streakUnit: "Streak",
      pinnedSection: "✦ Habits",
      otherSection: "Random Daily Quests",
      otherSectionSub: "Random daily quests",
      availableItems: "📜 Available Quests",
      itemSingular: "Quest",
      itemPlural: "Quests",
      itemLabel: "QUESTS",
      pinnedTag: "PINNED",
      pinnedHint: "Pinned daily quest",
      clickPrompt: "Click to complete",
      completedLabel: "Completed",
      rerollTitle: "Choose Quests to Replace",
      rerollMessage: "Choose 1 to 3 uncompleted non-pinned quests below. Only the selected quests will be replaced; the rest will stay unchanged.",
      rerollWarning: "Free once per day",
      rerollButton: "REROLL",
      rerollDone: "REROLLED",
      rerollComplete: "COMPLETED",
      rerollConfirm: "Replace Selected Quests",
      rerollSelectionHint: "You can replace only quests that have not been completed yet.",
      rerollSelectionCount: "Selected: {count}/3",
      rerollLimitReached: "You can select up to 3 quests.",
      cancelLabel: "Cancel",
      resetDaily: "🔄 Reset Daily",
      resetProgress: "🔥 Reset progress",
      notesButton: "📝 NOTES",
      notesTitle: "Private Notes",
      notesDesc: "Your notes are saved only for your profile on this device. Other users cannot see them.",
      notesSave: "Save Notes",
      closeLabel: "Close",
      tokenSection: "🪙 Token Vault",
      dailyQuestFreshBadge: "NEW",
      tokenUnit: "tokens",
            tokenIcon: "🪙",
      streakIcon: "🔥",
      dailyBoardIcon: "📜",
      habitsIcon: "📋",
      cityIcon: "🏙️",
      logsIcon: "✨",
      levelIcon: "⭐",
      freezeTitle: "Streak Freeze",
      freezeDesc: "Protect your streak for 1 day",
      freezeDetail: "If you complete 2 or fewer quests today, your streak won't reset. Active until midnight.",
      freezeActive: "ACTIVE TODAY",
      freezeSuccess: "Streak Protected!",
      freezeSuccessDetail: "Your streak is frozen until midnight.",
      freezeSuccessSub: "You won't lose your streak today even if you skip quests.",
      freezeAck: "Got it!",
      rerollShopTitle: "Extra Reroll",
      rerollShopDesc: "Reroll quests one more time today",
      rerollShopDetail: "Already used your daily reroll? Buy an extra one. Stacks — buy multiple for more rerolls.",
      rerollReady: "EXTRA REROLL",
      rerollReadyPlural: "EXTRA REROLLS",
      rerollReadySuffix: "READY",
      rerollFreeFirst: "Use Free Reroll First",
      replaceTitle: "Reroll All Pinned Quests",
      replaceDesc: "Swap all pinned quests at once",
      replaceDetail: "Click the ⟳ Reroll button directly on any pinned quest on the board to reroll all pinned quests. (Costs 7 in-game tokens, or Free once every 21 days)",
      replacePinned: "Currently pinned",
      buyPrefix: "Buy —",
      customizePrefix: "Customize —",
      notEnough: "Not Enough Tokens",
      leaderboard: "🏆 Leaderboard",
      leaderboardEmpty: "No heroes in the realm yet...",
      logSection: "✨ Battle Chronicles",
      logSub: "Latest exploits",
      logEmpty: "No chronicles written yet...",
      levelUpTitle: "Victory Unlocked",
      levelUpPrefix: "Level",
      levelUpMessage: "Your power rises and the world takes notice.",
      welcomeBack: "Welcome back, Player. Your journey continues...",
      newDay: "🌅 A new day dawns! Daily tasks have been refreshed!",
      rerolledLog: "🎲 Quests rerolled! New challenges await!",
      resetLog: "🌅 Daily quests reset! A new set of challenges awaits!",
      hardResetLog: "🔄 Complete reset! Starting fresh from Level 1...",
      onboardingTitle: "First Quest Setup",
      onboardingMessage: "Choose your nickname and 3 preferred quests. They stay pinned daily, and you can reroll all pinned quests once every 21 days for free, or for 7 in-game tokens.",
      onboardingAvatarHint: "Avatar is optional and can be changed later by clicking your portrait.",
      onboardingNickname: "Nickname",
      onboardingNicknamePlaceholder: "Username",
      onboardingPick: "Pick 3 Preferred Quests",
      onboardingSelected: "selected",
      onboardingBegin: "Start Adventure",
      onboardingSaving: "Saving...",
      onboardingSearch: "Search by quest name or description...",
      onboardingNoMatch: "No quests matched your search.",
      replacePinnedTitle: "Choose up to 3 quests",
      replacePinnedHeading: "Replace Pinned Quests",
      replacePinnedCost: "Cost: 7 in-game tokens",
      milestoneRunes: ["✓", "★", "🏆"],
      dailyResetLabel: "Daily reset at midnight in:",
      weekResetLabel: "Week reset in:",
      streakProtectedBadge: "🧊 Streak Protected",
      xpMultiplier: "XP multiplier",
      totalXpLabel: "Total XP",
      rankIcons: ["👑", "🥈", "🥉"],
      portraitUploadHint: "Click to upload image",
      themeLabel: "Theme"
    }
  },
  balance: {
    id: "balance",
    label: "Balance",
    description: "Calm wellness-inspired experience",
    icon: "🌿",
    fonts: { heading: "'Quicksand', sans-serif", body: "'Quicksand', sans-serif" },
    vocab: {
      appTitle: "🌿 GOHABIT 🌿",
      appSubtitle: "Nurture Your Growth",
      appTagline: "GoHabit",
      loginTitle: "Welcome to GoHabit",
      loginSubtitle: "Sign in with Google to continue your habit journey.",
      loginButton: "Login With Google",
      loginButtonApple: "Login With Apple",
      appleLoginComingSoonTitle: "Coming Soon",
      appleLoginComingSoonDesc: "Apple Sign-In is currently in development. Stay tuned!",
      loadingText: "Initializing world...",
      logoutTitle: "Abandon Quest?",
      logoutMessage: "Your progress is saved. You can return to the realm at any time.",
      logoutStay: "Stay",
      logoutConfirm: "Logout",
      deleteProfileButton: "Delete My Profile",
      deleteProfileTitle: "Delete Profile Permanently?",
      deleteProfileWarningBadge: "PERMANENT DATA DELETION",
      deleteProfileDesc: "This is a full and irreversible deletion of your profile and all your data: progress, XP, streak, habits, and quests.",
      deleteProfileCannotUndo: "After deletion, recovery is not possible.",
      deleteProfileConfirm: "Yes, Permanently Delete",
      deleteProfileCancel: "No, Keep My Profile",
      levelLabel: "Level",
      levelShort: "LEVEL",
      levelProgress: "Level Progress",
      xpLabel: "XP",
      dailyBoard: "Daily Board",
      currentStreak: "Current Streak",
      todaysItems: "Today's Quests",
      streakUnit: "Streak",
      pinnedSection: "✦ Habits",
      otherSection: "Random Daily Quests",
      otherSectionSub: "Random daily quests",
      availableItems: "🌿 Today's Quests",
      itemSingular: "Quest",
      itemPlural: "Quests",
      itemLabel: "QUESTS",
      pinnedTag: "PINNED",
      pinnedHint: "Pinned daily quest",
      clickPrompt: "Click to complete",
      completedLabel: "Completed",
      rerollTitle: "Choose Quests to Replace",
      rerollMessage: "Choose 1 to 3 uncompleted non-pinned quests below. Only the selected quests will be replaced; the rest will stay unchanged.",
      rerollWarning: "Free once per day",
      rerollButton: "REROLL",
      rerollDone: "REROLLED",
      rerollComplete: "COMPLETED",
      rerollConfirm: "Replace Selected Quests",
      rerollSelectionHint: "You can replace only quests that have not been completed yet.",
      rerollSelectionCount: "Selected: {count}/3",
      rerollLimitReached: "You can select up to 3 quests.",
      cancelLabel: "Cancel",
      resetDaily: "🔄 Reset Daily",
      resetProgress: "🔥 Reset progress",
      notesButton: "📝 NOTES",
      notesTitle: "Private Notes",
      notesDesc: "Your notes are saved only for your profile on this device. Other users cannot see them.",
      notesSave: "Save Notes",
      closeLabel: "Close",
      tokenSection: "🪙 Token Vault",
      dailyQuestFreshBadge: "NEW",
      tokenUnit: "tokens",
            tokenIcon: "🪙",
            streakIcon: "🔥",
      dailyBoardIcon: "📖",
      habitsIcon: "🪴",
      cityIcon: "🏡",
      logsIcon: "🍃",
      levelIcon: "✨",
      freezeTitle: "Streak Freeze",
      freezeDesc: "Protect your streak for 1 day",
      freezeDetail: "If you don't complete 4+ quests today, your streak won't reset. Active until midnight.",
      freezeActive: "ACTIVE TODAY",
      freezeSuccess: "Streak Protected!",
      freezeSuccessDetail: "Your streak is frozen until midnight.",
      freezeSuccessSub: "You won't lose your streak today even if you skip quests.",
      freezeAck: "Got it!",
      rerollShopTitle: "Extra Reroll",
      rerollShopDesc: "Reroll quests one more time today",
      rerollShopDetail: "Already used your daily reroll? Buy an extra one. Stacks — buy multiple for more rerolls.",
      rerollReady: "EXTRA REROLL",
      rerollReadyPlural: "EXTRA REROLLS",
      rerollReadySuffix: "READY",
      rerollFreeFirst: "Use Free Reroll First",
      replaceTitle: "Reroll All Pinned Quests",
      replaceDesc: "Swap all pinned quests at once",
      replaceDetail: "Click the ⟳ Reroll button directly on any pinned quest on the board to reroll all pinned quests. (Costs 7 in-game tokens, or Free once every 21 days)",
      replacePinned: "Currently pinned",
      buyPrefix: "Buy —",
      customizePrefix: "Customize —",
      notEnough: "Not Enough Tokens",
      leaderboard: "🏆 Leaderboard",
      leaderboardEmpty: "No heroes in the realm yet...",
      logSection: "✨ Battle Chronicles",
      logSub: "Latest exploits",
      logEmpty: "No chronicles written yet...",
      levelUpTitle: "Victory Unlocked",
      levelUpPrefix: "Level",
      levelUpMessage: "Your power rises and the world takes notice.",
      welcomeBack: "Welcome back, Player. Your journey continues...",
      newDay: "🌅 A new day dawns! Daily tasks have been refreshed!",
      rerolledLog: "🎲 Quests rerolled! New challenges await!",
      resetLog: "🌅 Daily quests reset! A new set of challenges awaits!",
      hardResetLog: "🔄 Complete reset! Starting fresh from Level 1...",
      onboardingTitle: "First Quest Setup",
      onboardingMessage: "Choose your nickname and 3 preferred quests. They stay pinned daily, and you can reroll all pinned quests once every 21 days for free, or for 7 in-game tokens.",
      onboardingAvatarHint: "Avatar is optional and can be changed later by clicking your portrait.",
      onboardingNickname: "Nickname",
      onboardingNicknamePlaceholder: "Username",
      onboardingPick: "Pick 3 Preferred Quests",
      onboardingSelected: "selected",
      onboardingBegin: "Start Adventure",
      onboardingSaving: "Saving...",
      onboardingSearch: "Search by quest name or description...",
      onboardingNoMatch: "No quests matched your search.",
      replacePinnedTitle: "Choose up to 3 quests",
      replacePinnedHeading: "Replace Pinned Quests",
      replacePinnedCost: "Cost: 7 in-game tokens",
      milestoneRunes: ["✓", "★", "🏆"],
      dailyResetLabel: "Daily reset at midnight in:",
      weekResetLabel: "Week reset in:",
      streakProtectedBadge: "🧊 Streak Protected",
      xpMultiplier: "XP multiplier",
      totalXpLabel: "Total XP",
      rankIcons: ["👑", "🥈", "🥉"],
      portraitUploadHint: "Click to upload image",
      themeLabel: "Theme"
    }
  },
  light: {
    id: "light",
    label: "Light",
    description: "Soft daylight interface inspired by modern wellness apps",
    icon: "☀️",
    fonts: { heading: "'Quicksand', sans-serif", body: "'Quicksand', sans-serif" },
    vocab: {
      appTitle: "☀️ GOHABIT ☀️",
      appSubtitle: "Small actions, bright progress",
      appTagline: "GoHabit",
      availableItems: "Today's Quests",
      tokenIcon: "🪙",
      streakIcon: "🔥",
      dailyBoardIcon: "📅",
      habitsIcon: "🪴",
      cityIcon: "🌤️",
      logsIcon: "📝",
      levelIcon: "🏅",
      themeLabel: "Theme"
    }
  }
};

export const themeIds = Object.keys(themes);
export default themes;




